### ISSUE TITLE
Trace Context (Oliver Egger (ahdis ag))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#155]
ch.fhir.ig.ch-epr-mhealth#3.0.0 /tracecontext.html

Discussion on EPD RU call 12.3.2024:
- For the client (primary system) the TraceContext is not mandatory
- For the server (endpoint) the tracecontext should be mandatory to generate if it is not added on all transactions and propagated to followup transactions.

Oliver Egger (ahdis ag)

**Comment by oliveregger** [comment]
this is already covered in the W3 specification, we should refer to that

**Comment by oliveregger** [comment]
https://www.w3.org/TR/trace-context/#processing-model
