### ISSUE TITLE
mCSD additional transaction for Feed

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-fhir#158]
low priority

**Comment by oliveregger** [comment]
will be prepared that this is ready for the projectathon

**Comment by oliveregger** [comment]
see also work related to IHE https://github.com/IHE/IT-Infrastructure/projects/2

**Comment by qligier** [comment]
Create, conditional update, conditional delete.

Support direct transactions and batch/transaction (which one is DSML2 BatchRequest?)

Structure the page like ITI-104, call it CH:mCSD-1

**Comment by qligier** [comment]
DSML2's batchRequest is behaving like a batch, each request has its own, independent response (successful or not).

**Comment by qligier** [comment]
Conditional update and conditional delete on the DN. To be discussed.

**Comment by qligier** [comment]
LDAP should not be made mandatory, mCSD could be implemented with a FHIR backend (or other database).

**Comment by qligier** [comment]
Use regular operations instead of conditional ones. The server is responsible for setting the resource id.
Add a section on the transaction page to describe some FHIR-to-LDAP requirements, comments, or recommendations.
