### ISSUE TITLE
MHD: Security Considerations: shall be able can this be shorted to shall? 

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-fhir#171]
Find Document Lists [ITI-66] and other transactions in MHD

Security Considerations: shall be able

can this be shorted to shall? 

or would be the meaning of shall be able be recommended?

IHE uses in ITI also the same language:
https://profiles.ihe.net/ITI/MHD/ITI-67.html

**Comment by msmock** [comment]
Yes. Shall is shorter and better.
