### ISSUE TITLE
Get Access Token [ITI-71] - patient id not escaped? (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#174]
ch.fhir.ig.ch-epr-fhir#4.0.0-ci-build /iti-71.html

The example jwt token https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/iti-71.html has the EPRS-SPID escaped:

`761337610411353650^^^&amp;2.16.756.5.30.1.127.3.10.3&amp;ISO`

should this not be?
`761337610411353650^^^&2.16.756.5.30.1.127.3.10.3&ISO`

I'm not aware of a requriement that json needs to escape the & character, and for CH:ATC we  don't have this requirement.

however IHE ITI BALP has also a double escped parameter, will raise the issue there too:

https://github.com/IHE/ITI.BasicAudit/issues/101

Oliver Egger, ahdis ag

**Comment by qligier** [comment]
The first EPR-SPID should read: `761337610411353650^^^&amp;2.16.756.5.30.1.127.3.10.3&amp;ISO`

**Comment by oliveregger** [comment]
Discussed at telco, adjust to unescaped.
