### ISSUE TITLE
Trace Context (telco 8.5)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#185]
ch.fhir.ig.ch-epr-fhir#4.0.0-ci-build /tracecontext.html

remove texts: according to the Change Proposal EHSEPDBEP-222 for A5E1.

telco 8.5

**Comment by ziegm** [comment]
define AuditEvent profile with slice TraceContext: according to the Change Proposal EHSEPDBEP-222 for A5E1.
