### ISSUE TITLE
Audit Examples together with IUA and and adapted to EPR requirements  

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-fhir#186]
Need to define Audit Examples/Profiles together with IUA and and adapted to EPR requirements

**Comment by qligier** [comment]
In the [Amendment 1 to Annex 5](https://www.fedlex.admin.ch/eli/oc/2023/221/de/annexes), §1.5.1:

1. The OID of the audit source shall be specified (`@AuditEnterpriseSiteID` in DICOM).
2. When an XDS document is described in the audit log, its confidentiality code shall be specified (if known) (`@ParticipantObjectSensitivity` in DICOM).
3. When a code from a Swiss value set is represented, its name shall be the value set OID (`@codeSystemName` in DICOM).

§1.6.4.3.5.1:

1. The first ActiveParticipant is the IHE XUA requirement.
2. The second element describes the main user (the subject of the XUA assertion)
    * ID of the user: GLN for a HCP, EPR-SPID for the patient, or the ID of the representative.
    * Real-world name of the user
    * Role of the user
3. The third element is required, if some other person acted on behalf of the main user
    * ID of the assistant or technical user
    * Real-world name of the assistant or technical user
    * Role of the assistant or technical user

**Comment by oliveregger** [comment]
> No need to map it (?)
leave it out

**Comment by qligier** [comment]
QL: need to provide an example

**Comment by oliveregger** [comment]
should we take https://profiles.ihe.net/ITI/BALP/content.html#35753-oauth---comprehensive-auditevent-record into consideration for defining what information should be audited out of the IUA (ch) token?

**Comment by oliveregger** [comment]
remove group/organization

**Comment by oliveregger** [comment]
PR with a "real" example

**Comment by oliveregger** [comment]
discussion with ms today:

we should add also the option possibilites for the basic token iua mappings to audit event

https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/iti-71.html#message-semantics-1
