### ISSUE TITLE
Useage of PersonalRelationship: Consistency between PIXV3, PDQV3 and PIXm, PDQm

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-epr-fhir#191]
According to the change proposal for EHSEPDBEP-245, the PersonalRelationship should not be used in context of the EPR.
PIXm and PDQm have to be consistent with the PIXV3 Feed and PDQV3 Query.

**Comment by oliveregger** [comment]
- Verify that the PIXm Feed does not allow sending contact information
- Verify that the PDQm response does not allow contact information.
