### ISSUE TITLE
Sequence Diagrams (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#192]
ch.fhir.ig.ch-epr-fhir#4.0.1-ballot /sequencediagrams.html

we miss a sequence diagram for the publishing as we have described here in the following gazelle test 

https://ehealthsuisse.ihe-europe.net/gazelle/testing/testsDefinition/viewTestPage.seam?id=13749&cid=86665

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
add info to changelog
