### ISSUE TITLE
Find Document References [ITI-67] - Add security considerations (Telco, 4.7.2024)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#196]
ch.fhir.ig.ch-epr-fhir#4.0.1-ci-build /iti-67.html

We need to add a sentence to add that policy enforcements are respected or used (CH:ADR). 

Telco, 4.7.2024

**Comment by oliveregger** [comment]
applies to iti-65 and ppq profiles too

**Comment by msmock** [comment]
resolved
