### ISSUE TITLE
CH PPQm: Consider changes according to CH:PPQ Release 2025

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-epr-fhir#203]

**Comment by oliveregger** [comment]
@dkotlaris do you know the date when those changes will come?

**Comment by dkotlaris** [comment]
@oliveregger we can already make all changes as pull requests and merge them once the changes have been accepted. The decision will be made in late October 2024.

**Comment by oliveregger** [comment]
@dkotlaris do you have any updates on this what we need to do

**Comment by dkotlaris** [comment]
Cosing this issue. The CH PPQm Profile is complete and in sync with CH PPQ.
