### ISSUE TITLE
CH MHD SubmissionSet Comprehensive (Quentin Ligier, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#211]
ch.fhir.ig.ch-epr-fhir#4.0.1-ci-build /StructureDefinition-ch-mhd-submissionset-comprehensive.html

At least 3 `extension`s are required, but only 2 slices are marked as required. The cardinality should be lowered to 2..*

Quentin Ligier, ahdis

**Comment by qligier** [comment]
https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/StructureDefinition-ch-mhd-submissionset-comprehensive-definitions.html#List.extension
