### ISSUE TITLE
consistency of the versions of the dependencies (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-epr-fhir#213]
Inconsistency example:

https://fhir.ch/ig/ch-epr-fhir/index.html#dependency-table
Mobile access to Health Documents (MHD)	ihe.iti.mhd -> **4.2.1**	

https://fhir.ch/ig/ch-epr-fhir/iti-65.html#referenced-standards
Mobile access to Health Documents (MHD), Rev. **4.2.1** – Trial-Implementation, August 2, 2023 

refers to https://profiles.ihe.net/ITI/MHD/index.html (current published version **4.2.2**)

**Comment by oliveregger** [comment]
- need to change the release date to 2024-05-18
- can we define in IG Publisher variables for markdown text that we could change the publication date in one place?

**Comment by qligier** [comment]
From [ig-guidance](https://build.fhir.org/ig/FHIR/ig-guidance/index.html), the dependencies version and date are not present in package.db, or in any of the liquid variables (defined in temp/pages/_data).
