### ISSUE TITLE
CH PPQm: Consistent transaction identifiers

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-epr-fhir#214]
To be discussed if "PPQ-3", "PPQ-4" and "PPQ-5" should be "CH:PPQ-3", "CH:PPQ-4" and "CH:PPQ-5" like for "CH:MHD-1".

Or if we discuss again to change to "CH:PPQm-1", "CH:PPQm-2", "CH:PPQm-3" and become independent to the PPQ profile.

**Comment by unixoid** [comment]
Usually, the first part of an IHE transaction ID is the ID of a whole IHE technical framework, not of a particular profile -- for example, both XDS and MHD transactions are called ITI-xx.  From this point of view, all Swiss national transactions may be called EPR-xx or similar.

**Comment by dkotlaris** [comment]
Yes, that would be a good idea. Let's discuss this next week in the expert group.

**Comment by dkotlaris** [comment]
Discussion in "Expertengruppe EPD Technik" of eHealth Suisse on 25 September 2024 (Oliver, Dmytro and Daniel):
In addition to the EPR, Switzerland is building a Swiss Health Dataspace in which the EPR will play an important role. IHE and HL7 FHIR will also be used for other projects. If we rename the Swiss transactions to e.g. "A Swiss Transaction [_EPR_-1]", then we will not be generic for other Swiss healthcare projects. Therefore, we should not make quick decisions on the naming of the transaction identifier for Swiss transactions. Therefore we close this issue and will come back to it later.
