### ISSUE TITLE
Cardinality of the SubmissionSet author

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-fhir#218]
https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/StructureDefinition-ch-mhd-submissionset-comprehensive.html

In the CHMhdSubmissionSetComprehensive profile, the `List.source` (mapped to `SubmissionSet.author`) is optional (`0..1`).
In the [Ergänzung 1 zum Anhang 5](https://www.fedlex.admin.ch/filestore/fedlex.data.admin.ch/eli/oce/2024/43/de/pdf-a/fedlex-data-admin-ch-eli-oce-2024-43-de-pdf-a.pdf) §1.2.4.2, the SubmissionSet.author is required.

**Comment by qligier** [comment]
https://ehealthsuisse.github.io/EPR-by-example/ProvideAndRegister/#submission-set, it says:

> The author element is optional in the EPR. If present, it shall convey the information on the person, which initiated the request.

It's inconsistent with Ergänzung 1 zum Anhang 5

**Comment by qligier** [comment]
In https://profiles.ihe.net/ITI/TF/Volume3/ch-4.2.html#4.2

> The author attribute defines a structure to hold its sub-attributes that are individually defined in Sections 4.2.3.1.4.1 through 4.2.3.1.4.5.
> authorPerson – zero or one
authorInstitution – zero or more
authorRole – zero or more
authorSpecialty – zero or more
authorTelecommunication – zero or more
At least an authorPerson, authorTelecommunication or authorInstitution sub-attribute shall be present when the author attribute is included in the metadata.

**Comment by qligier** [comment]
![image](https://github.com/user-attachments/assets/68bf5633-4326-4299-b955-1a4e484ea38d)

**Comment by oliveregger** [comment]
1. will be change to O with next revision of annex (accepted change)(
2. leave it as otpional
