### ISSUE TITLE
ITI-67: tokens in search params

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-fhir#221]
In [MHD](https://profiles.ihe.net/ITI/MHD/ITI-67.html#23674121-query-search-parameters)/[FHIR](https://hl7.org/fhir/R4/search.html#token), search parameters of type token are allowed to contain only the code or system values. This is not convertible to XDS, where the code and system have to be specified.

`[parameter]=[code]`, `[parameter]=|[code]` and `[parameter]=[system]|`.

Should CH EPR FHIR drop support for these tokens?

**Comment by qligier** [comment]
The XDS specification for ITI-18: https://profiles.ihe.net/ITI/TF/Volume2/ITI-18.html#3.18.4.1.2.3.4

**Comment by oliveregger** [comment]
Suggest to add some text in ITI-67 for that.

**Comment by oliveregger** [comment]
MS/QL/OE: need to come with wording

**Comment by qligier** [comment]
Proposition:

The search parameters of type [token](https://hl7.org/fhir/R4/search.html#token) SHALL contain both the system and the code.
