### ISSUE TITLE
Mobile Patient Identifier Cross-reference Query [ITI-83] - reduce targetSystem cardinality (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#223]
ch.fhir.ig.ch-epr-fhir#4.0.1-ballot /iti-83.html

>targetSystem	2..2
>SHALL be the Assigning authority of the community and the EPR-SPID.

The MHD query transactions requires with this version the EPR-SPID as a query identifier, therefore the MPI-PID by the Assigning authority of the community is not required for every usecase, suggest it to change to:

>targetSystem	1..2
>SHALL be the Assigning authority of the EPR-SPID and MAY be the Assigning authority of the community.

The conformance resources would need to be adapted too.

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
MS/QL/OE: proceed with this change
