### ISSUE TITLE
Patient Demographics Query for Mobile (PDQm) (OIiver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#224]
ch.fhir.ig.ch-epr-fhir#4.0.1-ballot /iti-pdqm.html

Currently the Swiss Specification requires ITI-78 Mobile Patient Demographics Query for the UseCase of Querying patient demographics. This works will, has however the disadvantage that the returned Patient will contain all identifiers assigned to the patient (local identifiers for the patient). 

IHE ITI introduced the  Patient Demographics Match [ITI-119] transaction, which would defines an operation where the result could be enforced to contain only the EPRS-PID identifier.

Propose that the transaction been switched.

OIiver Egger, ahdis ag

**Comment by oliveregger** [comment]
QL/MS/OE: switch to $match

**Comment by jkiddo** [comment]
I disagree with the statement "... returned Patient will contain all identifiers assigned to the patient (local identifiers for the patient)."

It will always be up to the discretion of the server/producer to filter and subset data according to the underlying security model in its response. The exact same rules apply to ITI-119. The underlying security model will take precedence in what is returned based on e.g. an access token. Arguing that ITI-119 is more secure/discloses less data than ITI-78 is not correct.
