### ISSUE TITLE
Traceparent: cross-community use in PIXm/PDQm

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-fhir#236]
In the 'Security Consideration' section of PIXm/PDQm transactions, the use of the traceparent header is described as:

> The Patient Demographics Supplier actor SHALL enforce a traceparent header to enable inspection of cross community transactions as defined in section [Trace Context header](https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/tracecontext.html).

There are no cross-community transactions for these profiles.

mCSD has the much simpler:

> For the traceparent header handling, refer to [Trace Context header](https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/tracecontext.html).

Edit: Also, is it expected from the responder to always include the traceparent header on the first response? (Not related to the cross-community wording)

**Comment by oliveregger** [comment]
The actors SHALL support a traceparent header handling as defined in section [Trace Context header](https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/tracecontext.html).

Need to adapt all transactions.

>Edit: Also, is it expected from the responder to always include the traceparent header on the first response? (Not related to the cross-community wording)

this is not finally decided yet, ongoing discussion.
