### ISSUE TITLE
The old IG "CH EPR mHealth" still exists and leads to confusion

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-epr-fhir#240]
The old IG "CH EPR mHealth" (e.g. https://fhir.ch/ig/ch-epr-mhealth/iti-mcsd.html) is still accessible.
Only the relevant IG  "CH EPR FHIR" (e.g. https://fhir.ch/ig/ch-epr-fhir/iti-mcsd.html) should be kept to avoid confusion.

**Comment by oliveregger** [comment]
Telco 19.10
- remove the canonical version files (not the versioned)
- try to redirect from versionless [https://fhir.ch/ig/ch-epr-mhealth](https://fhir.ch/ig/ch-epr-mhealth/...) to ch-epr-fhir

**Comment by oliveregger** [comment]
removed canonical version from fhir.ch (old verisons like https://fhir.ch/ig/ch-epr-mhealth/3.0.0/index.html are still available).
installed redirect from https://fhir.ch/ig/ch-epr-mhealth to ch-epr-fhir
