### ISSUE TITLE
IUA Support for technical user

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#45]
ch.fhir.ig.ch-epr-mhealth#1.1.0 /iti-71.html

According to chapter 3.1.6.1 it won't be possible to get a token for a the technical user (TCU). Does this mean that the ITI-65 / Provide Document Bundle transaction cannot be used by the TCU or only if a XUA SAML assertion is provided? 

Marco Studer, Cistec AG

**Comment by oliveregger** [comment]
Telco 5.1 limitation is correct, is not planned yet to introduce, but might be for a future release when the mhealth profiles are established

**Comment by msmock** [comment]
Add a OAuth flow for technical users. See SMART for services for example.

**Comment by msmock** [comment]
TODO list: 
- add the client credential grant type as MUST be supported by an Authorization Server
- only for read access 
- describe the requirements for the client credential grant in the text
-

**Comment by martinsmock** [comment]
Re-structure the document and use subsections for 

1. Client Credential grant type 
2. Authorization Code grant type

in Sections: 
- Messages 
- Expected Actions 
- usw. see IUA profile

**Comment by oliveregger** [comment]
fixed with d68dae0f7b05c61f9db9cada40fa66c6c3a1a793
