### ISSUE TITLE
Cross community access

### ISSUE THREAD

**Issue by msmock** [ehealthsuisse/ch-epr-fhir#92]
The communities shall provide the mobile endpoints for cross community access. These shall be secured by IUA JWT token. We need to provide and verify the corresponding flows.

**Comment by oliveregger** [comment]
difference is that ATC used EPR-SPID

**Comment by oliveregger** [comment]
a client connects to a community and the community handles the cross-community interactions between FHIR

**Comment by oliveregger** [comment]
Approach to discuss would be to add a "Aggregate Option" in the MHD Cons


PS -> MHD Endpoint (IC) -> MHD Query (RC)
          a.org                          b.org
                                             return DocumentReference with url ="b.org/....."

option 1)
        MHD Endoitn rewrites url "b.org/" -> "a.org/b/...."

option 2)
         while doing the request a.org has a FORWARD-HOST/URL , please return the result already with a.org/b/

let's evaluate option 1 or option 2

**Comment by oliveregger** [comment]
1. check receiver - recipient -> should be only recipient
2. provide diagram
